# Generated by Django 5.2.1 on 2025-05-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0004_alter_block_options_remove_block_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='notes',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='block_index',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default='2025-05-18'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
