# Generated by Django 5.2.1 on 2025-05-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0005_rename_donor_email_donation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='source_id',
            field=models.CharField(max_length=100),
        ),
    ]
