# Generated by Django 5.2.1 on 2025-05-18 04:44

import capstone_project.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0007_donation_rejection_reason_donation_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.JSONField(default=list)),
                ('pending_transactions', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('manual', 'Manual')], default='gcash', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default=capstone_project.models.generate_transaction_id, max_length=100, unique=True),
        ),
    ]
