# Generated by Django 5.2.1 on 2025-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0010_donation_rejection_reason_donation_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='submitted_by',
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
