# Generated by Django 5.1.7 on 2025-05-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0014_create_forum_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='donation_receipts/'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='capstone_project.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Attendance',
                'verbose_name_plural': 'Event Attendances',
                'unique_together': {('event', 'member')},
            },
        ),
    ]
