# Generated by Django 5.2.1 on 2025-05-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0015_donation_receipt_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone_project.council'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
