# Generated by Django 5.2.1 on 2025-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0016_donation_council_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Check to make the donation anonymous on the blockchain.'),
        ),
    ]
