# Generated by Django 5.1.7 on 2025-05-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0018_user_e_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
