# Generated by Django 5.1.7 on 2025-05-27 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0019_user_join_reason_user_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recruited', models.DateField(default=django.utils.timezone.now)),
                ('recruited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruited_by', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recruiter', 'recruited')},
            },
        ),
    ]
