# Generated by Django 5.1.7 on 2025-05-28 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0021_notification_content_notification_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_manual_addition', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_recruited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_recruited_by', to=settings.AUTH_USER_MODEL)),
                ('new_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_recruitments', to=settings.AUTH_USER_MODEL)),
                ('original_recruited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_recruited_by', to=settings.AUTH_USER_MODEL)),
                ('original_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_recruitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
