# Generated by Django 5.1.7 on 2025-05-28 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0022_recruitmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_recruitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RecruitmentHistory',
        ),
    ]
