# Generated by Django 5.1.7 on 2025-05-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0020_remove_donation_is_anonymous'),
        ('capstone_project', '0023_recruitment_added_by_recruitment_is_manual_and_more'),
    ]

    operations = [
    ]
