# Generated by Django 5.1.7 on 2025-12-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0027_add_final_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='council_joined_date',
            field=models.DateField(blank=True, help_text='Date when user joined current council', null=True),
        ),
        migrations.CreateModel(
            name='CouncilPositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('officer', 'Officer'), ('member', 'Member'), ('pending', 'Pending')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_project.council')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_position_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
