# Generated by Django 5.1.7 on 2025-12-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0002_donation_donor'),
        ('capstone_project', '0028_user_council_joined_date_councilpositionhistory'),
    ]

    operations = [
    ]
