# Generated by Django 5.2.1 on 2025-05-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0008_blockchain_remove_donation_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='chain',
        ),
    ]
