# Generated by Django 5.2.6 on 2025-09-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0026_event_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_attendance',
            field=models.BooleanField(default=True, help_text='Enable attendance tracking for this event'),
        ),
    ]
