# Generated by Django 5.2.1 on 2025-11-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0027_event_enable_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='capstone_project.event'),
        ),
    ]
