# Generated by Django 5.2.1 on 2025-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0028_donation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether the donor wishes to remain anonymous in public records.'),
        ),
    ]
