# Generated by Django 5.2.1 on 2025-12-06 22:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0031_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fundraising goal for this event (optional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
    ]
