# Generated by Django 5.2.1 on 2025-12-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0032_event_goal_amount_event_raised_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fundraising goal in PHP (optional)', max_digits=12, null=True),
        ),
    ]
