# Generated by Django 5.1.7 on 2025-12-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0033_alter_event_goal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='goal_amount',
        ),
        migrations.AddField(
            model_name='council',
            name='location_barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='location_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='location_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='location_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount raised for this event', max_digits=10),
        ),
    ]
