# Generated by Django 5.1.7 on 2025-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0034_remove_event_goal_amount_council_location_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='council_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='council',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
