# Generated by Django 5.1.7 on 2025-12-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0035_council_council_number_alter_council_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='council_number',
        ),
    ]
