# Generated by Django 5.1.7 on 2025-05-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0017_user_marital_status_user_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='e_signatures/'),
        ),
    ]
