# Generated by Django 5.2.1 on 2025-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0017_donation_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_anonymous',
        ),
    ]
