# Generated by Django 5.2.1 on 2025-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0018_remove_donation_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Check to make the donation anonymous on the blockchain.'),
        ),
    ]
