# Generated by Django 5.1.7 on 2025-08-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_project', '0025_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
