# Generated by Django 5.2.1 on 2025-12-10 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone_project", "0026_event_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="location_barangay",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="council",
            name="location_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="council",
            name="location_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="council",
            name="location_street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="council",
            name="location_zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="capstone_project.event",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Whether the donor wishes to remain anonymous in public records.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="enable_attendance",
            field=models.BooleanField(
                default=True, help_text="Enable attendance tracking for this event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="raised_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount raised for this event",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("pending_proposal", "Pending Proposal/Member"),
                    ("donation_received", "Donation Received"),
                    ("event_today", "Event Happening Today"),
                    ("donation_quota_reached", "Donation Quota Reached"),
                    ("proposal_accepted", "Proposal Accepted"),
                    ("proposal_rejected", "Proposal Rejected"),
                    ("pending_member_approval", "Pending Member Approval"),
                    ("officer_inactive", "Officer Inactive"),
                    ("council_moved", "Moved to New Council"),
                    ("promoted_to_officer", "Promoted to Officer"),
                    ("demoted_to_member", "Demoted to Member"),
                    ("recruiter_assigned", "Assigned as Recruiter"),
                    ("event_attended", "Event Attended"),
                    ("member_inactive", "Member Inactive"),
                    ("member_moved", "Moved to New Council"),
                    ("member_promoted", "Promoted to Officer"),
                    ("member_demoted", "Demoted to Member"),
                    ("member_recruiter", "Assigned as Recruiter"),
                    ("member_attended", "Event Attended"),
                    ("forum_message", "Forum Message"),
                ],
                default="forum_message",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_council",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="capstone_project.council",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="capstone_project.event",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_about_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="council",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
